name: Generate go.mod & go.sum

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Generate go.mod and go.sum
        run: |
          go mod init github.com/Khaymat/portfolio
          go mod tidy

      - name: Commit & Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add go.mod go.sum
          git commit -m "Generate go.mod & go.sum"
          git push
